### ISSUE TITLE
Old links needs to be regarded on the new portal

### ISSUE THREAD

**Issue by isimluk** [isimluk/openscap-portal#1]
Particularly, we have many other sources referencing following pages:

  http://www.open-scap.org/page/Main_Page (many sources, out of our reach)
  http://www.open-scap.org/page/SCE (many pages, some out of our reach)
  http://www.open-scap.org/page/Contribute (our openscap-base documentation)

**Comment by mpreisler** [comment]
#12 blocks this.

**Comment by mpreisler** [comment]
All of these are redirected now. #12 is fixed as well.

The `Redirection` plugin tracks 404s so we will be able to add more redirects as people encounter 404 errors. See `Tools->Redirection` in Wordpress Dashboard.
