### ISSUE TITLE
Provide .htaccess redirects for SCE and SCE result file

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#12]
The old URLs need to stay alive forever if possible. Putting it here so that we don't forget before GA.

```
/page/SCE -> /features/other-standards/sce/
/page/SCE_result_file -> /features/other-standards/sce/#sce-result-file
```

**Comment by ybznek** [comment]
We also need to redirect
/page/Xccdf-1.1-tailoring -> (not known now)

**Comment by mpreisler** [comment]
I have experience with this so I can do it if I get access to the app. @lhorakov ?

**Comment by mpreisler** [comment]
I managed to do this without `.htaccess`. See `Tools->Redirection` in the Wordpress dashboard.

The final pages may change but the redirects are in place.
