### ISSUE TITLE
Tailoring vs. Customization

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#13]
In previous discussions around `SCAP Workbench` we decided to use the term `customization` instead of tailoring. It is more commonly understood, especially for non-native speakers.

In the portal however, the page is called Tailoring and we primarily use the term tailoring in there.

IMO either we decide that the decision in the past is wrong and workbench changes or the portal should change.

**Comment by jan-cerny** [comment]
I would use `customization` on portal, because Workbench has got a button "Customize", not "Tailor"

**Comment by lhorakov** [comment]
All tailoring keywords had been changed into Customization. Also footer, header and links. Please check it and close.

**Comment by mpreisler** [comment]
Thx
