### ISSUE TITLE
Generate HTML guides for Firefox and Java at static.open-scap.org

### ISSUE THREAD

**Issue by jan-cerny** [isimluk/openscap-portal#15]
"Choosing policy" page points to HTML guides for RHELs and Fedora, but it would be nice to be able to link there also HTML guides for Firefox and Java, because we mention these policies in section "Security policies available in the SCAP Security Guide".

**Comment by mpreisler** [comment]
http://static.open-scap.org contains guides that `make install` in SSG installs.

Please sort this out in SSG itself.
