### ISSUE TITLE
Link "NIST certified" to NVD NIST

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#16]
https://nvd.nist.gov/scap/validation/128.cfm

**Comment by msrubar** [comment]
http://openscap-lhorakov.rhcloud.com/tools/openscap-base/#references

**Comment by mpreisler** [comment]
I am talking about the footer text.

The footer text should either link to that or to nvd.nist.gov

**Comment by lhorakov** [comment]
Your Issue has been solved by Me. 
The result can be seen anywhere at portal.

**Comment by mpreisler** [comment]
Hi, the link works fine but the link text is misleading IMO. OpenSCAP is not "NVD NIST", it is NVD NIST certified.

I suggest "We are NIST certified" as the link text.

**Comment by lhorakov** [comment]
Corrected. I was confused by the issues title.

**Comment by mpreisler** [comment]
Thx
