### ISSUE TITLE
Proper wordpress theme name, author, license

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#17]
The OpenSCAP WP theme says it is authored by Zac Gordon who AFAIK is the author of the parent theme.

http://openscap-lhorakov.rhcloud.com/wp-content/themes/wpbootstrap-openscap/style.css

The header of this file needs to be changed.

**Comment by lhorakov** [comment]
I'll change it, but also the wanted to have this information somewhere, it was written in one tutorial have to put bootstrap into wordpress. So I thought that it's important to refer it also because of authors' rights. Author's I mean bootstrap design.

**Comment by lhorakov** [comment]
Dear developer, the issue is solved:
/*
Theme Name: WP Bootstrap - OpenSCAP
Author: OpenSCAP developer team, contributing Lenka Horakova
Author URI: http://lenkahorakova.com/
Tags: openscap, wordpress, bootstrap
*/
