### ISSUE TITLE
Installation commands for openSUSE and SUSE

### ISSUE THREAD

**Issue by abergmann** [isimluk/openscap-portal#205]
We've noticed that the SCAP Security Guide page is missing installation procedures for **openSUSE** and **SUSE Linux Enterprise**.

https://www.open-scap.org/security-policies/scap-security-guide/

We would like to add the following two logos with the `zypper` installation command.
(The **SUSE** logo is not made for white backgrounds like this one here, but would work on the open-scap.org page. If needed we could provide different color versions and sizes.)

<img src="https://brand.suse.com/assets/img/brand/logo-block-03.png" alt="SUSE" width="50" />&nbsp;&nbsp;&nbsp;<img src="https://raw.githubusercontent.com/openSUSE/artwork/master/logos/official/logo-color.png" alt="openSUSE" width="50" /> 

`zypper install scap-security-guide`

Mockup:

<img src="https://user-images.githubusercontent.com/4102163/135614178-14963ccd-00ed-4a5f-8fd2-6d9023474fd5.png" width="350" />

The same goes for the OpenSCAP download page:

https://www.open-scap.org/download/

OpenSCAP Base:

`zypper install openscap-utils`

SCAP Workbench (only **openSUSE** atm):

`zypper install scap-workbench`

SCAP Security Guide:

`zypper install scap-security-guide`
<br>

Logo reference links:
* https://brand.suse.com/assets/img/brand/logo-block-03.png
* https://raw.githubusercontent.com/openSUSE/artwork/master/logos/official/logo-color.png

**Comment by ggbecker** [comment]
Hello, I have updated the https://www.open-scap.org/security-policies/scap-security-guide/ webpage with installing instructions for openSUSE and SLES. Can you please check if it's they way you intended to be? Then we can move on to the other sections.

**Comment by abergmann** [comment]
Hi Gabriel,

The webpage is almost perfect! 👍 Only the details for **openSUSE** need to be adjusted.

----------------------
You can install **SCAP Security Guide** on **openSUSE Leap** using **zypper**:
```
zypper install scap-security-guide
```
You can install **SCAP Security Guide** on **openSUSE Tumbleweed** using **zypper**:
```
zypper install scap-security-guide
```
----------------------

There is also the download section that is missing the install commands for ...

<img src="https://user-images.githubusercontent.com/4102163/136231661-427bae5d-b576-4572-9fb3-a6015cad9852.png" width="350">

* OpenSCAP Base `zypper install openscap-utils`
* SCAP Workbench (**openSUSE** only) `zypper install scap-workbench`
* SCAP Security Guide `zypper install scap-security-guide`

I think it would be sufficient to have only **SUSE Linux Enterprise** and **openSUSE** selectable here.

**Comment by ggbecker** [comment]
I was working on adding these options to the download page. Now let me update the items according to your suggestions.

**Comment by ggbecker** [comment]
I think it should be all good. Please check it and if it's enough you may close the issue.

**Comment by ggbecker** [comment]
There was one last fix `SUSE Enterprise Linux Server` -> `SUSE Linux Enterprise Server` (wrong word order) pointed out by `blaine`.

**Comment by abergmann** [comment]
Perfect! Thanks for that.

Ticket can be closed now.
