### ISSUE TITLE
Dead link for DISA STIGs

### ISSUE THREAD

**Issue by ralphie79** [isimluk/openscap-portal#207]
[OpenSCAP Base page](https://www.open-scap.org/tools/openscap-base) contains a dead link titled '[DISA STIGs](http://iase.disa.mil/stigs/Pages/index.aspx)' pointing to "http://iase.disa.mil/stigs/Pages/index.aspx".   I believe the correct link for this information is actually at: [http://iase.disa.mil/stigs/Pages/index.aspx](https://public.cyber.mil/stigs/downloads/)

**Comment by ggbecker** [comment]
Fixed. Edited the link to: https://public.cyber.mil/stigs/downloads/
