### ISSUE TITLE
Access denied on static.open-scap.org

### ISSUE THREAD

**Issue by tbalbers** [isimluk/openscap-portal#211]
Hi guys,
Sorry if this isn't the right place for this, I wasn't able to find any contact info on 'static'.

When on this page:
https://static.open-scap.org/ssg-guides/ssg-rhel8-guide-index.html

I get an error trying to view Profile: CIS Red Hat Enterprise Linux 8 Benchmark for Level 2 - Workstation :

Forbidden
You don't have permission to access /domains/static.open-scap.org/ssg-guides/ssg-rhel8-guide-cis_workstation_l2.html on this server.

It seems that other pages are working fine.

Any help is much appreciated,

Thanks,

**Comment by jan-cerny** [comment]
Thanks, it should be fixed now.
