### ISSUE TITLE
Save nature (and bandwidth) with SVG

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#22]
http://openscap-lhorakov.rhcloud.com/wp-content/uploads/2015/07/banner2.png
http://openscap-lhorakov.rhcloud.com/wp-content/uploads/2015/07/banner3.png

Lets battle the trend of web pages getting insanely huge. These two images take roughly 1.7 MB. That's dangerously close to the size of the entire Doom1 PC game - see https://pbs.twimg.com/media/CLLGenwWgAAZAVv.png. Both images are full of hard-to-compress gradients that would take a tiny fraction of the size in SVG format.

AFAIK the only problem is IE8 and lower, see http://caniuse.com/#feat=svg The probability that somebody would have a 4k monitor and IE8 is very close to 0.

It's not just bandwidth, the sizes make the page very RAM hungry and sluggish on slower devices. The devices have to decompress this huge PNG and store each pixel's color. Then the images have to be scaled using bilinear filtering.

**Comment by lhorakov** [comment]
I will change this. But! we are already using bootstraps lot of MBs, so that isn't such problem, but I agree, I can change it. I will.

**Comment by ybznek** [comment]
Text files are compressed by webserver during transfer to client.

**Comment by lhorakov** [comment]
Issue solved ;)

**Comment by mpreisler** [comment]
thx
