### ISSUE TITLE
Change description of 'other-standards'

### ISSUE THREAD

**Issue by ybznek** [isimluk/openscap-portal#23]
http://openscap-lhorakov.rhcloud.com/features/standards/

'Other standards' page will contain SCAP standards which are not implemented by openscap and standards implemented by openscap but not in SCAP standards.

The page is not still completed, so do not solve the ticket before it will be.

**Comment by jan-cerny** [comment]
Also see Issue #38

**Comment by mpreisler** [comment]
@jan-cerny provided basis for the new text, I just rephrased it a little. This is now fixed.
