### ISSUE TITLE
Black square is displayed when selecting numbered item under "How OpenSCAP Ecosystem Can Help" section in Vulnerability Assessment page.  Remove it.

### ISSUE THREAD

**Issue by iankko** [isimluk/openscap-portal#29]
Description of problem:

Selecting (clicking at) some of "1" .. "5" circles in ```How OpenSCAP Ecosystem Can Help``` section of the ```Vulnerability Assessment``` page displays black square around the circle when selected. Remove it
(see the picture below for clarification).

![black_square_around_selected_item_cropped](https://cloud.githubusercontent.com/assets/8414918/9907064/ab6f0f46-5c8d-11e5-8bd6-b433bf5dd0f8.png)

**Comment by lhorakov** [comment]
Done
