### ISSUE TITLE
Pointer style cursor

### ISSUE THREAD

**Issue by msrubar** [isimluk/openscap-portal#37]
Screens was taken from the [SCAP-Workbench](http://openscap-lhorakov.rhcloud.com/tools/scap-workbench/) page. ![Image of Yaktocat](https://msrubar.fedorapeople.org/mouse-pointer-bug1.png)
![Image of Yaktocat](https://msrubar.fedorapeople.org/mouse-pointer-bug2.png)

**Comment by lhorakov** [comment]
It's because one is link and one isn't. With link you goes away from page, without you stays.
