### ISSUE TITLE
"Other standards" page heading and first paragraph does not make me sense

### ISSUE THREAD

**Issue by jan-cerny** [isimluk/openscap-portal#38]
Heading of the page says:
> We know you care about other standards too

It is nice that we know that, but we do not give you any solution :-)

And also:

> For security compliance, there are also other standards different from SCAP. We make sure, our solution is well interoperable with them.

I do not understand how is OpenSCAP interoperable with SACM or SWID if OpenSCAP do not implement these.

**Comment by jan-cerny** [comment]
Also see Issue #23

**Comment by isimluk** [comment]
These are good remarks, Jan. I agree our wording should be improved.

**Comment by isimluk** [comment]
The main reason for us having the other-standards page is to educate user. To help users understand various pieces (scap, sacm, fipc, cc) and how they fit together.

**Comment by jan-cerny** [comment]
@isimluk I think the wording is very very good now. Closing.
