### ISSUE TITLE
/features/scap-components/#xccdf-11-tailoring is missing

### ISSUE THREAD

**Issue by isimluk** [isimluk/openscap-portal#48]
At the components page, there is `XCCDF 1.1 tailoring example.` The example however, seems to relate to SCE and that is confusing.

Short introduction to `XCCDF 1.1 Tailoring` is however missing. Also, we need this anchor `/features/scap-components/#xccdf-11-tailoring` for redirects (see #12).

The old portal at http://www.open-scap.org/page/Xccdf-1.1-tailoring reads:
```
XCCDF 1.1 Tailoring extension

NOTE: Text on this page will apply when openscap 0.9.12 is released.

openscap 0.9.12 introduces an extension to XCCDF 1.1 specification that allows tools and users to create tailoring files even for XCCDF 1.1 content. 
```

**Comment by isimluk** [comment]
@jan-cerny , can you please take a look into this?

**Comment by isimluk** [comment]
@jan-cerny what is status of this?

I think the text has been improved! However, we still have the XCCDF-1.1 as a sub-paragraph of SCE. I think it should be major paragraph.

**Comment by jan-cerny** [comment]
@isimluk I am very sorry, I have somehow ignored that I have been assigned to this. I also think that it should be main paragraph. I didn't want it to be under SCE, maybe I have confused <h3> with <h4> (or a similar mistake) and Lenka probably has done the graphics according to that. I will try to fix it.

**Comment by jan-cerny** [comment]
Fixed.
