### ISSUE TITLE
Tutorial: Customizing SSG

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#49]
http://openscap-lhorakov.rhcloud.com/resources/documentation/customizing-scap-security-guide-for-your-use-case/

Go over *specific* customization. Show examples of something practical. SSH root login is a very common compromise. Password length is also very common.

Sources:
http://static.open-scap.org/scap-workbench-1.1/

**Comment by msrubar** [comment]
I did a little review of your text. I hope it'll be helpful.

https://msrubar.fedorapeople.org/review.odt

**Comment by jan-cerny** [comment]
@msrubar That is awesome! It is definitely very helpful. Thank you very much! Could I review some of your texts?

**Comment by jan-cerny** [comment]
I think the tutorial is ready.

**Comment by msrubar** [comment]
Definitely. You can do the review of those:
https://openscap-lhorakov.rhcloud.com/resources/documentation/evaluate-remote-machine-for-usgcb-compliance-with-scap-workbench/
https://openscap-lhorakov.rhcloud.com/resources/documentation/make-a-rhel7-server-compliant-with-pci-dss/

Any feedback is welcomed!

**Comment by isimluk** [comment]
Perfect! I think we can close this ticket now. (?)

Thanks!
