### ISSUE TITLE
Help to complete the list of projects, organizations and vendors who uses openscap

### ISSUE THREAD

**Issue by msrubar** [isimluk/openscap-portal#59]
https://openscap-lhorakov.rhcloud.com/features/open-source-community/

I think it the look something like [this](https://www.openstack.org/foundation/companies/). Maybe pvrabec and shawn could also help with it?

**Comment by mpreisler** [comment]
- Red Hat
- SUSE - https://www.suse.com/documentation/suse_manager/book_susemanager_user/data/ch-openscap.html
- Oracle Solaris - https://blogs.oracle.com/darren/entry/compliance_reporting_with_scap
- Oracle OEL
- NSA SIMP - https://github.com/simp/pupmod-simp-openscap
- govready - https://github.com/GovReady/govready

I may add more later.

**Comment by isimluk** [comment]
Added preupgrade, ManageIQ on the page.

Closing this for now.
