### ISSUE TITLE
<title> always contains "Bootstrap"

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#6]
It should contain the title of the page instead.

**Comment by lhorakov** [comment]
ReTitled to "OpenSCAP Portal"

**Comment by mpreisler** [comment]
I expected the title to change as you browse different pages.

For example `Resources | OpenSCAP Portal`

**Comment by lhorakov** [comment]
High expectations. :laughing: 
I'll make it real, somehow

**Comment by lhorakov** [comment]
It's done! Everything for you Martin ;)

**Comment by mpreisler** [comment]
Nice! Thx
