### ISSUE TITLE
Create a youtube channel

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#7]

**Comment by lhorakov** [comment]
https://www.youtube.com/channel/UCDbj6NfYqXdocy9ET9i1Wjg

Needed:
- all usable videos
- I can add administrators if you want
- Description of channel
- connect with Twitter when the previous points will be done

**Comment by mpreisler** [comment]
Can we get a nicer URL?

**Comment by lhorakov** [comment]
For now we cannot.

To get a custom URL for your channel, your account needs to be in good standing and meet a few other requirements:

    500 or more subscribers
    Channels is at least 30 days old
    Channel has uploaded a photo for the channel icon
    Channel has uploaded channel art

You can also qualify for a custom URL by linking and verifying your official webpage with your channel or +Page.

**Comment by isimluk** [comment]
Resources:
 * https://youtu.be/XI1QcQL4qQ8
 * https://youtu.be/WCVBNb6nfR8
 * https://youtu.be/caSIW4-yhUk
 * https://youtu.be/qGYWO2THPXM
 * https://youtu.be/FMtASybl16k
 * https://youtu.be/caSIW4-yhUk
 * https://www.youtube.com/watch?v=X7yY49-Y7Xk
 * https://www.youtube.com/watch?v=p4uNlzYld-Y

I hope, I haven't forget any.

Perhaps it makes sense to sort these resources semantically. Does youtube channel allow us to do some kind of ordering?

**Comment by lhorakov** [comment]
I have created new gmail account for having youtube channel on that one, and not on my personal gmail. Here's new link for channel https://www.youtube.com/channel/UCjiZ-sIQhPBHRIt3PRj60yA/feed also already with list of videos. We can publish it now, and use it also on Portal. And let's collect subscribers! :D

**Comment by isimluk** [comment]
Perfect. Thanks!

We now only needs to amend the footer to link to this youtube channel.

**Comment by lhorakov** [comment]
It's done (CSS outline:none;)
