### ISSUE TITLE
Point out to the mainling list at the bottom of each tutorial

### ISSUE THREAD

**Issue by isimluk** [isimluk/openscap-portal#80]
This is for discussion.

On my blog, I have found that people are eager to provide feedback or ask good questions in the comments section.

Having comments enabled on portal, however, would be hard to manage/respond timely. What about having link to the mailing-list at the bottom of each tutorial/post?

**Comment by mpreisler** [comment]
We love the mailing list but I think for most people it's easier to write a comment. They can login with their twitter or other account and type it immediately, without subscribing.

Wordpress can be set-up to send notifications about new comments in the queue. I use that for my blog and it's manageable.

**Comment by isimluk** [comment]
Closing, I just find this is duplicate to #39.
