### ISSUE TITLE
present sat-6/openscap video instead of screenshot

### ISSUE THREAD

**Issue by isimluk** [isimluk/openscap-portal#83]
At the "systems management" page we present a screenshot of foreman_openscap, however we have nice video we can present istead: https://www.youtube.com/watch?v=p4uNlzYld-Y&list=PLHYsrwTE3Rofwk_cc7641QNhSF8JzPprE&index=8

**Comment by mpreisler** [comment]
http://openscap-lhorakov.rhcloud.com/tools/systems-management/

Done.
