### ISSUE TITLE
Improve static.open-scap.org index page

### ISSUE THREAD

**Issue by mpreisler** [isimluk/openscap-portal#9]
UX, visuals, design.

See #4. @mpreisler can provide access to the OpenShift instance and Jenkins job.

**Comment by jan-cerny** [comment]
Missing link to fedora guide at static.open-scap.org, although it is available on http://static.open-scap.org/ssg-guides/ssg-fedora-guide-index.html

**Comment by mpreisler** [comment]
> Missing link to fedora guide at static.open-scap.org, although it is available on http://static.open-scap.org/ssg-guides/ssg-fedora-guide-index.html

Fixed, thanks

**Comment by isimluk** [comment]
@lhorakov has already provided nice visual design for this.

Closing.
